### PR TITLE
Fix: FlightComputer's attitude controller is unstable and spinning

### LINKED ISSUE #559: flight computer spins randomly not holding directions
First bug report, hope I cover most of the bases.

KSP 1203 on Windows, 32 and 64bit tested.  Issue exists with no mods except RemoteTech 1.16.11-492.  I have other mods installed but simplified it to isolate the problem.

I'm a brand new RemoteTech user so I tried searching around to see that I'm just not doing something wrong.  I think it might be a bug, but it's so serious I'm confused why I'd be the first one to say so... maybe it's just me.

I create a basic probe craft, launch it and try to circularize with the flight computer.  Per the tutorial, I click GRD+ then EXEC after I've setup the maneuver.  The craft begins to spin and rotate never settles on a direction.  It doesn't look like it's even trying to find a particular point, it looks very random.  When it executed the burn, the direction is still wrong and the maneuver isn't anywhere nearly correctly executed.

Here is the craft and the save.
https://gist.github.com/gnivler/037d20163d5d68d9af6aefd18540106c

Thank you for your efforts!

### PR DESCRIPTION
**Pull request by d4rksh4de**
Fixes #559

### CODE REVIEW

File: src/RemoteTech/FlightComputer/PIDController.cs [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+/// Proportional controller for KSP autopilots
+/// </summary>
+
+using System;
+
+namespace RemoteTech.FlightComputer
+{
+    // -----------------------------------------------
+    // Copied from MechJeb master on 18.04.2016
+    public class PIDControllerV3 : IConfigNode
```
Comment (tomekpiotrowski) [inline src/RemoteTech/FlightComputer/PIDController.cs]: I'd prefer if file name and class name were the same. Either `PIDController` or `PIDControllerV3` is fine by me, just make them the same.

File: src/RemoteTech/FlightComputer/FlightCore.cs [hunk 2]
```diff
@@ -176,58 +176,110 @@ public static void SteerShipToward(Quaternion target, FlightCtrlState c, FlightC
...
-            Vector3d normFactor;
-            normFactor.x = (torque.x != 0 ? momentOfInertia.x / torque.x : 0.0);
-            normFactor.y = (torque.y != 0 ? momentOfInertia.y / torque.y : 0.0);
-            normFactor.z = (torque.z != 0 ? momentOfInertia.z / torque.z : 0.0);
-            normFactor = SwapYZ(normFactor);
+            // ( MoI / available torque ) factor:
+            Vector3d NormFactor = Vector3d.Scale(momentOfInertia, torque.Invert()).Reorder(132);
 
-            // Find out the real shorter way to turn were we want to.
+            // Find out the real shorter way to turn were we wan to.
```
Comment (tomekpiotrowski) [inline src/RemoteTech/FlightComputer/FlightCore.cs]: 'want' was changed to 'wan'
